// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use Supabase's session pooler for Prisma CLI operations. The application
    // client continues to use DATABASE_URL (the transaction pooler) in utils/db.
    url: process.env["DIRECT_URL"],
  },
});
